### ISSUE TITLE
Aura upgrade 

### ISSUE THREAD

**Issue by Puffy120** [S-B99/KAMI#183]
Make it so you can hit while you eat something that you have in your right hand

**Comment by S-B99** [comment]
This is already a thing, unless you mean your offand?

**Comment by Puffy120** [comment]
> This is already a thing, unless you mean your offand?

LOL yeah I meant left hand I'm retarded

**Comment by S-B99** [comment]
I just looked at the aura code, and actually, when eating minecraft cancels hitting. So the function isn't actually done by kami, but offhand is an exception. Because you're not hitting anyways, just put your gapps or whatever beside your sword and switch it? See #60 for it to automatically switch back when you're done, unless it's a 32k so it already does
